### ISSUE TITLE
Carousel demo broken

### ISSUE THREAD

**Issue by KevinBatdorf** [rcbyr/keen-slider-sandboxes#1]
https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/misc/carousel/react-typescript?file=/src/App.tsx

![Screen Shot 2022-12-03 at 5 44 15 PM](https://user-images.githubusercontent.com/1478421/205465141-4e64b702-d4ed-42b4-9097-47503d791b82.png)

**Comment by rcbyr** [comment]
Thank you very much for noticing me about that. Fixed
